export const FETCH_TRADE_MESSAGES = "FETCH_TRADE_MESSAGES";
export const SET_TRADE_MESSAGES = "SET_TRADE_MESSAGES";
export const SET_RATE_CHANGES = "SET_RATE_CHANGES";
export const SET_COUNTRY_TRANSACTIONS = "SET_COUNTRY_TRANSACTIONS";